### ISSUE TITLE
Why webpack?

### ISSUE THREAD

**Issue by igoreliasm** [pamtbaau/angular5-electron-sqlite3-bootstrap4-webpack#1]
Why did you prefer to use a webpack file and not a own angular resource?

**Comment by pamtbaau** [comment]
When I started creating my first angular/electron app I forked a simple demo app. That app happened to be based on Webpack... And angular.io had a nice [tutorial](https://angular.io/guide/webpack) on angular/webpack as well.

The knowledge I've gained on webpack now comes in handy when playing with angular-cli which happens to use webpack under the hood. That webpack config can be ejected and altered in order for angular-cli and electron to work together.

Not sure what you mean with "own angular resource"...
